[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'kevinw/pyflakes-vim'
on_ft = 'python'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = 'python'
# 一般設定

[[plugins]]
repo = 'Shougo/neocomplete.vim'
insert = 1 

