theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "net"
device = "enp0s25"
ip = true
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "battery"
device="BAT1"
interval = 10
show = "both"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
